CC = gcc
CFLAGS = -Wall -Wextra -pedantic
TARGET = assignment3
TARGET_DEPS = 0300722fMath.c
all: $(TARGET)

$(TARGET): $(TARGET)
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c $(TARGET_DEPS)  

clean:
	rm $(TARGET)
